name: Release devcontainer features

on:
    push:
        branches: main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v2
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: devcontainers/action@v1
              with:
                  publish-features: "true"
                  base-path-to-features: "./src"
