name: Release devcontainer features

on:
    push:
        branches: main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish devcontainer features
              uses: devcontainers/action@v1
              with:
                  publish-features: "true"
                  base-path-to-features: "./features"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish devcontainer templates
              uses: devcontainers/action@v1
              with:
                  publish-templates: "true"
                  base-path-to-templates: "./templates"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
