on:
    push:
        branches: main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v2
            - uses: devcontainers/action@v1
              with:
                  publish-features: "true"
                  base-path-to-features: "./src"
